[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "SNOquery"
version = "0.0.1"
authors = [
  { name="Owen Dwyer", email="owen.dwyer@gtc.ox.ac.uk" },
]
description = "A package for querying the SNOMED ontology"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/owen-dwyer/SNOquery"
Issues = "https://github.com/owen-dwyer/SNOquery/issues"

dependencies = [
  requests >= 2.32.3,
]